### ISSUE TITLE
Name your project

### ISSUE THREAD

**Issue by tahadostifam** [rezavafadar/ChatApp-ts-express-socketio-react#1]
Give it a dedicated name.
Something like [Rezagram](https://github.com/tahadostifam/Tahagram) :]

**Comment by rezavafadar** [comment]
No bro, this is just a sample project for learning :)

**Comment by rezavafadar** [comment]
> @rezavafadar This is a long name. U can use the short ones like: ChatApp, Websockets-chat-app

yes, you're right.
